# -*- coding: utf-8 -*-
"""Netflix_EDA_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIbfKWiZ7xqySSdpjZ1KSmQziCuiSZrK

# **Netflix Movies & TV Shows - Exploratory Data Analysis (EDA)**

## **Project Overview**

This project performs Exploratory Data Analysis (EDA) on the Netflix Movies and TV Shows dataset. The goal of this analysis is to uncover patterns, trends, and insights related to Netflix content using statistical summaries and visualizations.

The analysis focuses on:
- Content distribution between Movies and TV Shows
- Country-wise content production
- Release year trends
- Ratings and genre analysis
- Missing value analysis
- Content growth patterns

## **Objectives**

- Understand the structure of the dataset
- Analyze content trends and distributions
- Identify important patterns and relationships
- Visualize data using charts and graphs
- Generate meaningful business insights

## **Technologies Used**

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Google Colab

## *Importing Required Libraries*

In this step, the necessary Python libraries are imported for data manipulation, analysis, and visualization. These libraries help in handling datasets, performing statistical analysis, and creating graphical representations of the data.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## *Loading the Dataset*

The Netflix Movies and TV Shows dataset is loaded into a Pandas DataFrame for analysis. The dataset contains information about Netflix content such as title, type, release year, rating, country, and genre.
"""

dataset = pd.read_csv('netflix_titles.csv')

dataset.head()

"""## *Exploring the Dataset*

In this step, the structure and properties of the dataset are explored. This includes checking the number of rows and columns, understanding data types, and identifying missing values present in the dataset.
"""

dataset.shape

dataset.columns

dataset.info()

dataset.dtypes

"""## *Data Cleaning*

Data cleaning is performed to improve the quality of the dataset before analysis. This includes checking for duplicate records and identifying missing values in important columns.
"""

dataset.isnull().sum()

plt.figure(figsize=(10,6))

sns.heatmap(dataset.isnull(), cbar=False, cmap='viridis')

plt.title("Missing Values Heatmap")

plt.show()

dataset.duplicated().sum()

dataset = dataset.drop_duplicates()

dataset.shape

"""## *Missing Value Analysis*

This section analyzes missing values present in the dataset. Missing data can affect the quality of analysis and visualizations. Understanding missing values helps identify incomplete records and data quality issues.
"""

missing_values = dataset.isnull().sum()

missing_values

missing_percentage = (dataset.isnull().sum() / len(dataset)) * 100

missing_percentage.sort_values(ascending=False)

"""### *Missing Values Percentage Visualization*

The following visualization represents the percentage of missing values present in different columns of the dataset.
"""

missing_percentage = missing_percentage[missing_percentage > 0]

plt.figure(figsize=(10,6))

missing_percentage.sort_values().plot(kind='barh')

plt.xlabel("Percentage of Missing Values")
plt.ylabel("Columns")

plt.title("Missing Values Percentage by Column")

plt.show()

"""### *Observation*

The dataset contains missing values primarily in the `director`, `cast`, and `country` columns. The `director` column has the highest percentage of missing values. These missing values are common in real-world datasets and can impact analysis if not properly handled.

## *Statistical Analysis*

Statistical analysis helps summarize and understand the important characteristics of the dataset. This section explores the distribution of Netflix content based on content type, ratings, release years, and other categorical features.
"""

dataset.describe(include='all')

"""### *Movies vs TV Shows Distribution*

This analysis compares the number of Movies and TV Shows available in the Netflix dataset.
"""

dataset['type'].value_counts()

"""### *Most Common Content Ratings*

This analysis identifies the most frequently occurring Netflix content ratings in the dataset.
"""

dataset['rating'].value_counts()

"""### *Release Year Analysis*

This analysis explores the distribution of Netflix content based on release years.
"""

dataset['release_year'].describe()

"""### *Top Content Producing Countries*

This analysis identifies countries contributing the highest amount of Netflix content.
"""

dataset['country'].value_counts().head(10)

"""## *Content Type Distribution*

This visualization compares the number of Movies and TV Shows available on Netflix. It helps understand the dominant type of content present in the dataset.
"""

plt.figure(figsize=(6,5))

sns.countplot(x='type', data=dataset)

plt.title("Movies vs TV Shows Distribution")

plt.xlabel("Content Type")
plt.ylabel("Count")

plt.show()

"""## *Top 10 Content Producing Countries*

This visualization highlights the countries contributing the highest amount of content to Netflix.
"""

top_countries = dataset['country'].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top_countries.index,
    y=top_countries.values
)

plt.title("Top 10 Content Producing Countries")

plt.xlabel("Country")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()

"""## *Content Release Trend Over the Years*

This visualization shows how Netflix content releases have changed over time.
"""

plt.figure(figsize=(12,6))

dataset['release_year'].value_counts()\
.sort_index().plot()

plt.title("Netflix Content Release Trend")

plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.show()

"""## *Most Common Netflix Ratings*

This visualization displays the most frequently occurring content ratings available on Netflix.
"""

plt.figure(figsize=(10,6))

sns.countplot(
    y='rating',
    data=dataset,
    order=dataset['rating'].value_counts().index
)

plt.title("Distribution of Netflix Ratings")

plt.xlabel("Count")
plt.ylabel("Rating")

plt.show()

"""# **Insights & Findings**

## *Key Insights*

1. Movies dominate Netflix content compared to TV Shows, indicating that Netflix primarily focuses on movie distribution.

2. The United States contributes the highest amount of Netflix content, followed by countries such as India and the United Kingdom.

3. Netflix content releases increased significantly after the year 2000, with rapid growth observed after 2015.

4. The most common content rating on Netflix is `TV-MA`, showing that a large portion of content targets mature audiences.

5. Certain columns such as `director`, `cast`, and `country` contain missing values, which is common in real-world datasets.

6. Netflix contains content spanning many decades, with release years ranging from 1925 to 2021.

7. The dataset demonstrates strong diversity in genres, countries, and content types available on the platform.

## **Conclusion**

This Exploratory Data Analysis (EDA) project analyzed the Netflix Movies and TV Shows dataset to uncover patterns, trends, and insights related to Netflix content. The analysis revealed that Movies dominate the platform, the United States produces the highest amount of content, and Netflix content releases have grown rapidly in recent years.

Various statistical summaries and visualizations were used to better understand content distribution, ratings, release trends, and missing values present in the dataset. The project demonstrates the importance of data exploration and visualization in understanding real-world datasets and generating meaningful business insights.
"""